### ISSUE TITLE
Template ot Found on Debian Jessie

### ISSUE THREAD

**Issue by LondonAppDev** [saltstack-formulas/jenkins-formula#57]
When I try and run this on my Debian Jessie server, I get this output:

```
vagrant@deploy:~$ sudo salt '*' state.highstate
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'deploy.local': ['Rendering SLS \'base:apps.jenkins\' failed: Jinja error: jenkins/map.jinja\nTraceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "<template>", line 1, in top-level template code\n  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 144, in get_source\n    raise TemplateNotFound(template)\nTemplateNotFound: jenkins/map.jinja\n\n; line 1\n\n---\n{% from "jenkins/map.jinja" import jenkins with context %}    <======================\n\njenkins_group:\n  group.present:\n    - name: {{ jenkins.group }}\n    - system: True\n[...]\n---']}
ERROR: Minions returned with non-zero exit code
```

**Comment by gravyboat** [comment]
I'm assuming since you closed this you found the error?

**Comment by LondonAppDev** [comment]
Yes, thank you @gravyboat. For the benefit of others with the same issue, it was because I put the jenkins formula in a sub directory (I'm pretty new to Salt).
